name: frontend-svelte
on:
  push:
    branches:
      - master
    paths:
      - 'frontend-svelte/**'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: './frontend-svelte'
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: ${{env.working-directory}}
    - run: npm run build
      working-directory: ${{env.working-directory}}
    - uses: actions/upload-artifact@v2
      with:
        name: frontend-svelte
        path: ${{env.working-directory}}/public/
