name: frontend-svelte
on:
  push:
    branches:
      - master
    paths:
      - 'frontend-svelte/**'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: './frontend/svelte'
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: ${{env.working-directory}}
    - run: npm run build
      working-directory: ${{env.working-directory}}
    - uses: actions/upload-artifact@v2
      with:
        name: frontend-svelte
        path: ${{env.working-directory}}/public/
    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v0.0.1-preview
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_BEACH_097478403 }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
        action: "upload"
        ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
        # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
        app_location: "/frontend/svelte/" # App source code path
        api_location: "api" # Api source code path - optional
        app_artifact_location: "public" # Built app content directory - optional
        ###### End of Repository/Build Configurations ######
